# Generated by Django 3.1.14 on 2023-09-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-f0b4c51c58b943cdb8d1d9be7adffa82', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-2040f6691c194ccfb5c05f4c87974337', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
